package swam
package wasi

import java.nio.ByteBuffer

import swam.impl.Pointer

object Types {

	// This is an autogenerated file, do not change it

	object subclockflagsFlags extends Enumeration {
		val subscription_clock_abstime = Value(0)
	}

	type ciovec_array = Array[ciovec]
	type exitcode = u32

	case class `prestat`(mem: ByteBuffer, offset: Int) extends WASI_STRUCT { // UNION
		val `dir` = prestat_dir(mem, offset + 0)

		def write() = {
			dir.write()
		}
	}

	type inode = u64
	type fd = Int

	object adviceEnum extends Enumeration {
		val `normal`, `sequential`, `random`, `willneed`, `dontneed`, `noreuse` = Value
	}

	type s64 = Long
	type u8 = Byte

	case class `fdstat`(mem: ByteBuffer, offset: Int) extends WASI_STRUCT {
		val `fs_filetype` = mem.get(offset + 0)

		val `fs_flags` = mem.getShort(offset + 1)

		val `fs_rights_base` = mem.getLong(offset + 3)

		val `fs_rights_inheriting` = mem.getLong(offset + 11)


		def write() = {
			mem.put(offset + 0, `fs_filetype`)

			mem.putShort(offset + 1, `fs_flags`)

			mem.putLong(offset + 3, `fs_rights_base`)

			mem.putLong(offset + 11, `fs_rights_inheriting`)

		}
	}

	case class `ciovec`(mem: ByteBuffer, offset: Int) extends WASI_STRUCT {
		val `buf` = new Pointer[u8](offset, (i) => mem.get(i)
			, (i, r) => mem.put(i, `r`)
		)
		val `buf_len` = mem.getInt(offset + 4)


		def write() = {
			mem.putInt(offset, `buf`.offset)
			mem.putInt(offset + 4, `buf_len`)

		}
	}

	object signalEnum extends Enumeration {
		val `none`, `hup`, `int`, `quit`, `ill`, `trap`, `abrt`, `bus`, `fpe`, `kill`, `usr1`, `segv`, `usr2`, `pipe`, `alrm`, `term`, `chld`, `cont`, `stop`, `tstp`, `ttin`, `ttou`, `urg`, `xcpu`, `xfsz`, `vtalrm`, `prof`, `winch`, `poll`, `pwr`, `sys` = Value
	}

	type dirnamlen = u32
	type userdata = u64

	case class `subscription_clock`(mem: ByteBuffer, offset: Int) extends WASI_STRUCT {
		val `id` = mem.getInt(offset + 0)

		val `timeout` = mem.getLong(offset + 4)

		val `precision` = mem.getLong(offset + 12)

		val `flags` = mem.getShort(offset + 20)


		def write() = {
			mem.putInt(offset + 0, `id`)

			mem.putLong(offset + 4, `timeout`)

			mem.putLong(offset + 12, `precision`)

			mem.putShort(offset + 20, `flags`)

		}
	}

	object eventtypeEnum extends Enumeration {
		val `clock`, `fd_read`, `fd_write` = Value
	}

	type filesize = u64
	type u32 = Int
	type filedelta = s64

	object errnoEnum extends Enumeration {
		val `success`, `2big`, `acces`, `addrinuse`, `addrnotavail`, `afnosupport`, `again`, `already`, `badf`, `badmsg`, `busy`, `canceled`, `child`, `connaborted`, `connrefused`, `connreset`, `deadlk`, `destaddrreq`, `dom`, `dquot`, `exist`, `fault`, `fbig`, `hostunreach`, `idrm`, `ilseq`, `inprogress`, `intr`, `inval`, `io`, `isconn`, `isdir`, `loop`, `mfile`, `mlink`, `msgsize`, `multihop`, `nametoolong`, `netdown`, `netreset`, `netunreach`, `nfile`, `nobufs`, `nodev`, `noent`, `noexec`, `nolck`, `nolink`, `nomem`, `nomsg`, `noprotoopt`, `nospc`, `nosys`, `notconn`, `notdir`, `notempty`, `notrecoverable`, `notsock`, `notsup`, `notty`, `nxio`, `overflow`, `ownerdead`, `perm`, `pipe`, `proto`, `protonosupport`, `prototype`, `range`, `rofs`, `spipe`, `srch`, `stale`, `timedout`, `txtbsy`, `xdev`, `notcapable` = Value
	}

	object lookupflagsFlags extends Enumeration {
		val symlink_follow = Value(0)
	}

	type timestamp = u64
	type size = u32

	case class `dirent`(mem: ByteBuffer, offset: Int) extends WASI_STRUCT {
		val `d_next` = mem.getLong(offset + 0)

		val `d_ino` = mem.getLong(offset + 8)

		val `d_namlen` = mem.getInt(offset + 16)

		val `d_type` = mem.get(offset + 20)


		def write() = {
			mem.putLong(offset + 0, `d_next`)

			mem.putLong(offset + 8, `d_ino`)

			mem.putInt(offset + 16, `d_namlen`)

			mem.put(offset + 20, `d_type`)

		}
	}

	case class `subscription_fd_readwrite`(mem: ByteBuffer, offset: Int) extends WASI_STRUCT {
		val `file_descriptor` = mem.getInt(offset + 0)


		def write() = {
			mem.putInt(offset + 0, `file_descriptor`)

		}
	}

	case class `event`(mem: ByteBuffer, offset: Int) extends WASI_STRUCT {
		val `userdata` = mem.getLong(offset + 0)

		val `error` = mem.getShort(offset + 8)

		val `type` = mem.get(offset + 10)

		val `fd_readwrite` = event_fd_readwrite(mem, offset + 11)

		def write() = {
			mem.putLong(offset + 0, `userdata`)

			mem.putShort(offset + 8, `error`)

			mem.put(offset + 10, `type`)

			fd_readwrite.write()
		}
	}

	case class `filestat`(mem: ByteBuffer, offset: Int) extends WASI_STRUCT {
		val `dev` = mem.getLong(offset + 0)

		val `ino` = mem.getLong(offset + 8)

		val `filetype` = mem.get(offset + 16)

		val `nlink` = mem.getLong(offset + 17)

		val `size` = mem.getLong(offset + 25)

		val `atim` = mem.getLong(offset + 33)

		val `mtim` = mem.getLong(offset + 41)

		val `ctim` = mem.getLong(offset + 49)


		def write() = {
			mem.putLong(offset + 0, `dev`)

			mem.putLong(offset + 8, `ino`)

			mem.put(offset + 16, `filetype`)

			mem.putLong(offset + 17, `nlink`)

			mem.putLong(offset + 25, `size`)

			mem.putLong(offset + 33, `atim`)

			mem.putLong(offset + 41, `mtim`)

			mem.putLong(offset + 49, `ctim`)

		}
	}

	object filetypeEnum extends Enumeration {
		val `unknown`, `block_device`, `character_device`, `directory`, `regular_file`, `socket_dgram`, `socket_stream`, `symbolic_link` = Value
	}

	object sdflagsFlags extends Enumeration {
		val rd = Value(0)
		val wr = Value(1)
	}

	case class `subscription`(mem: ByteBuffer, offset: Int) extends WASI_STRUCT {
		val `userdata` = mem.getLong(offset + 0)

		val `u` = subscription_u(mem, offset + 8)

		def write() = {
			mem.putLong(offset + 0, `userdata`)

			`u`.write()
		}
	}

	type string = String

	object fstflagsFlags extends Enumeration {
		val atim = Value(0)
		val atim_now = Value(1)
		val mtim = Value(2)
		val mtim_now = Value(3)
	}

	object roflagsFlags extends Enumeration {
		val recv_data_truncated = Value(0)
	}

	type dircookie = u64
	type iovec_array = Array[iovec]

	object riflagsFlags extends Enumeration {
		val recv_peek = Value(0)
		val recv_waitall = Value(1)
	}

	case class `event_fd_readwrite`(mem: ByteBuffer, offset: Int) extends WASI_STRUCT {
		val `nbytes` = mem.getLong(offset + 0)

		val `flags` = mem.getShort(offset + 8)


		def write() = {
			mem.putLong(offset + 0, `nbytes`)

			mem.putShort(offset + 8, `flags`)

		}
	}

	type u64 = Long

	case class `subscription_u`(mem: ByteBuffer, offset: Int) extends WASI_STRUCT { // UNION
		val `clock` = subscription_clock(mem, offset + 0)
		val `fd_read` = subscription_fd_readwrite(mem, offset + 22)
		val `fd_write` = subscription_fd_readwrite(mem, offset + 26)

		def write() = {
			clock.write()
			fd_read.write()
			fd_write.write()
		}
	}

	object clockidEnum extends Enumeration {
		val `realtime`, `monotonic`, `process_cputime_id`, `thread_cputime_id` = Value
	}

	case class `iovec`(mem: ByteBuffer, offset: Int) extends WASI_STRUCT {
		val `buf` = new Pointer[u8](offset, (i) => mem.get(i)
			, (i, r) => mem.put(i, `r`)
		)
		val `buf_len` = mem.getInt(offset + 4)


		def write() = {
			mem.putInt(offset, `buf`.offset)
			mem.putInt(offset + 4, `buf_len`)
		}
	}

	object oflagsFlags extends Enumeration {
		val creat = Value(0)
		val directory = Value(1)
		val excl = Value(2)
		val trunc = Value(3)
	}

	object whenceEnum extends Enumeration {
		val `set`, `cur`, `end` = Value
	}

	type siflags = u16
	type linkcount = u64

	object rightsFlags extends Enumeration {
		val fd_datasync = Value(0)
		val fd_read = Value(1)
		val fd_seek = Value(2)
		val fd_fdstat_set_flags = Value(3)
		val fd_sync = Value(4)
		val fd_tell = Value(5)
		val fd_write = Value(6)
		val fd_advise = Value(7)
		val fd_allocate = Value(8)
		val path_create_directory = Value(9)
		val path_create_file = Value(10)
		val path_link_source = Value(11)
		val path_link_target = Value(12)
		val path_open = Value(13)
		val fd_readdir = Value(14)
		val path_readlink = Value(15)
		val path_rename_source = Value(16)
		val path_rename_target = Value(17)
		val path_filestat_get = Value(18)
		val path_filestat_set_size = Value(19)
		val path_filestat_set_times = Value(20)
		val fd_filestat_get = Value(21)
		val fd_filestat_set_size = Value(22)
		val fd_filestat_set_times = Value(23)
		val path_symlink = Value(24)
		val path_remove_directory = Value(25)
		val path_unlink_file = Value(26)
		val poll_fd_readwrite = Value(27)
		val sock_shutdown = Value(28)
	}

	object preopentypeEnum extends Enumeration {
		val `dir` = Value
	}

	object eventrwflagsFlags extends Enumeration {
		val fd_readwrite_hangup = Value(0)
	}

	object fdflagsFlags extends Enumeration {
		val append = Value(0)
		val dsync = Value(1)
		val nonblock = Value(2)
		val rsync = Value(3)
		val sync = Value(4)
	}

	type device = u64
	type u16 = Short

	case class `prestat_dir`(mem: ByteBuffer, offset: Int) extends WASI_STRUCT {
		val `pr_name_len` = mem.getInt(offset + 0)


		def write() = {
			mem.putInt(offset + 0, `pr_name_len`)

		}
	}

}